/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/modalRestaurante`; params?: Router.UnknownInputParams; } | { pathname: `/components/PostCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/PostComposerModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/reserva_usuario`; params?: Router.UnknownInputParams; } | { pathname: `/screens/BuscarLayer`; params?: Router.UnknownInputParams; } | { pathname: `/screens/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/screens/chat`; params?: Router.UnknownInputParams; } | { pathname: `/screens/evento`; params?: Router.UnknownInputParams; } | { pathname: `/screens/favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/screens/feed`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/mapa`; params?: Router.UnknownInputParams; } | { pathname: `/screens/perfil-amigo`; params?: Router.UnknownInputParams; } | { pathname: `/screens/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/screens/reservas`; params?: Router.UnknownInputParams; } | { pathname: `/screens/restaurante`; params?: Router.UnknownInputParams; } | { pathname: `/screens/social`; params?: Router.UnknownInputParams; } | { pathname: `/screens/splash`; params?: Router.UnknownInputParams; } | { pathname: `/screens/welcome`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/modalRestaurante`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PostCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PostComposerModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/reserva_usuario`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/BuscarLayer`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/evento`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/favoritos`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/feed`; params?: Router.UnknownOutputParams; } | { pathname: `/screens`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/mapa`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/perfil-amigo`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/reservas`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/restaurante`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/social`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/welcome`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/modalRestaurante${`?${string}` | `#${string}` | ''}` | `/components/PostCard${`?${string}` | `#${string}` | ''}` | `/components/PostComposerModal${`?${string}` | `#${string}` | ''}` | `/components/reserva_usuario${`?${string}` | `#${string}` | ''}` | `/screens/BuscarLayer${`?${string}` | `#${string}` | ''}` | `/screens/cadastro${`?${string}` | `#${string}` | ''}` | `/screens/chat${`?${string}` | `#${string}` | ''}` | `/screens/evento${`?${string}` | `#${string}` | ''}` | `/screens/favoritos${`?${string}` | `#${string}` | ''}` | `/screens/feed${`?${string}` | `#${string}` | ''}` | `/screens${`?${string}` | `#${string}` | ''}` | `/screens/login${`?${string}` | `#${string}` | ''}` | `/screens/mapa${`?${string}` | `#${string}` | ''}` | `/screens/perfil-amigo${`?${string}` | `#${string}` | ''}` | `/screens/perfil${`?${string}` | `#${string}` | ''}` | `/screens/reservas${`?${string}` | `#${string}` | ''}` | `/screens/restaurante${`?${string}` | `#${string}` | ''}` | `/screens/social${`?${string}` | `#${string}` | ''}` | `/screens/splash${`?${string}` | `#${string}` | ''}` | `/screens/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/modalRestaurante`; params?: Router.UnknownInputParams; } | { pathname: `/components/PostCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/PostComposerModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/reserva_usuario`; params?: Router.UnknownInputParams; } | { pathname: `/screens/BuscarLayer`; params?: Router.UnknownInputParams; } | { pathname: `/screens/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/screens/chat`; params?: Router.UnknownInputParams; } | { pathname: `/screens/evento`; params?: Router.UnknownInputParams; } | { pathname: `/screens/favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/screens/feed`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/mapa`; params?: Router.UnknownInputParams; } | { pathname: `/screens/perfil-amigo`; params?: Router.UnknownInputParams; } | { pathname: `/screens/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/screens/reservas`; params?: Router.UnknownInputParams; } | { pathname: `/screens/restaurante`; params?: Router.UnknownInputParams; } | { pathname: `/screens/social`; params?: Router.UnknownInputParams; } | { pathname: `/screens/splash`; params?: Router.UnknownInputParams; } | { pathname: `/screens/welcome`; params?: Router.UnknownInputParams; };
    }
  }
}
